<?php
// @codingStandardsIgnoreFile
// @codeCoverageIgnoreStart
// this is an autogenerated file - do not edit
spl_autoload_register(
    function($class) {
        static $classes = null;
        if ($classes === null) {
            $classes = array(
                'library\\book\\booktest' => '/unit/ValueObjects/BookTest.php',
                'library\\configurationtest' => '/unit/ConfigurationTest.php',
                'library\\exceptions\\invalidbookexceptiontest' => '/unit/Exceptions/InvalidBookExceptionTest.php',
                'library\\handler\\xmlformprocessortest' => '/unit/xmlhandler/XmlFormProcessorTest.php',
                'library\\handler\\xmlquerytest' => '/unit/xmlhandler/XmlQueryTest.php',
                'library\\processor\\addbookprocessortest' => '/unit/Processors/AddBookProcessorTest.php',
                'library\\processor\\errorpageprocessortest' => '/unit/processors/ErrorPageProcessorTest.php',
                'library\\requests\\abstractrequesttest' => '/unit/Request/AbstractRequestTest.php',
                'library\\responder\\htmlresponsetest' => '/unit/Responder/HtmlResponseTest.php',
                'library\\responder\\uritest' => '/unit/Responder/UriTest.php',
                'library\\routers\\routertest' => '/unit/Routers/RouterTest.php',
                'library\\session\\sessiontest' => '/unit/Session/SessionTest.php'
            );
        }
        $cn = strtolower($class);
        if (isset($classes[$cn])) {
            require __DIR__ . $classes[$cn];
        }
    }
);
// @codeCoverageIgnoreEnd
