<?php
// @codingStandardsIgnoreFile
// @codeCoverageIgnoreStart
// this is an autogenerated file - do not edit
spl_autoload_register(
    function($class) {
        static $classes = null;
        if ($classes === null) {
            $classes = array(
                'library\\book\\booktest' => '/ValueObjects/BookTest.php',
                'library\\exceptions\\invalidbookexceptiontest' => '/Exceptions/InvalidBookExceptionTest.php',
                'library\\factories\\configurationtest' => '/setup/ConfigurationTest.php',
                'library\\factories\\factorytest' => '/setup/FactoryTest.php',
                'library\\handler\\xmlformprocessortest' => '/xmlhandler/XmlFormProcessorTest.php',
                'library\\handler\\xmlquerytest' => '/xmlhandler/XmlQueryTest.php',
                'library\\processor\\addbookprocessortest' => '/processors/AddBookProcessorTest.php',
                'library\\processor\\errorpageprocessortest' => '/processors/ErrorPageProcessorTest.php',
                'library\\requests\\postrequesttest' => '/request/AbstractRequestTest.php',
                'library\\responder\\htmlresponsetest' => '/routing/HtmlResponseTest.php',
                'library\\responder\\OLDRouterTest' => '/routing/OLDRouterTestest.php',
                'library\\responder\\uritest' => '/routing/UriTest.php'
            );
        }
        $cn = strtolower($class);
        if (isset($classes[$cn])) {
            require __DIR__ . $classes[$cn];
        }
    }
);
// @codeCoverageIgnoreEnd
