<?php
// @codingStandardsIgnoreFile
// @codeCoverageIgnoreStart
// this is an autogenerated file - do not edit
spl_autoload_register(
    function($class) {
        static $classes = null;
        if ($classes === null) {
            $classes = array(
                'library\\book\\book' => '/book/Book.php',
                'library\\processor\\addbookprocessor' => '/processors/AddBookProcessor.php',
                'library\\processor\\displaybookformprocessor' => '/processors/DisplayBookFormProcessor.php',
                'library\\processor\\errorpageprocessor' => '/processors/ErrorPageProcessor.php',
                'library\\processor\\libraryprocessor' => '/processors/LibraryProcessor.php',
                'library\\processor\\processor' => '/processors/Processor.php',
                'library\\requests\\abstractrequest' => '/requests/AbstractRequest.php',
                'library\\requests\\getrequest' => '/requests/GetRequest.php',
                'library\\requests\\postrequest' => '/requests/PostRequest.php',
                'library\\routing\\htmlresponse' => '/routing/HtmlResponse.php',
                'library\\routing\\router' => '/routing/Router.php',
                'library\\routing\\uri' => '/routing/Uri.php',
                'library\\setup\\configuration' => '/setup/Configuration.php',
                'library\\setup\\factory' => '/setup/Factory.php',
                'library\\xmlhandler\\xmleditor' => '/xmlhandler/XmlEditor.php',
                'library\\xmlhandler\\xmlexceptionprocessor' => '/xmlhandler/XmlExceptionProcessor.php',
                'library\\xmlhandler\\xmlformprocessor' => '/xmlhandler/XmlFormProcessor.php',
                'library\\xmlhandler\\xmlquery' => '/xmlhandler/XmlQuery.php'
            );
        }
        $cn = strtolower($class);
        if (isset($classes[$cn])) {
            require __DIR__ . $classes[$cn];
        }
    }
);
// @codeCoverageIgnoreEnd
