<?php
// @codingStandardsIgnoreFile
// @codeCoverageIgnoreStart
// this is an autogenerated file - do not edit
spl_autoload_register(
    function($class) {
        static $classes = null;
        if ($classes === null) {
            $classes = array(
                'library\\abstractrequest' => '/AbstractRequest.php',
                'library\\addbookformvalidation' => '/AddBookFormValidation.php',
                'library\\addbookprocessor' => '/AddBookProcessor.php',
                'library\\errorpageprocessor' => '/ErrorPageProcessor.php',
                'library\\factory' => '/Factory.php',
                'library\\getrequest' => '/GetRequest.php',
                'library\\htmlresponse' => '/HtmlResponse.php',
                'library\\libraryprocessor' => '/LibraryProcessor.php',
                'library\\postrequest' => '/PostRequest.php',
                'library\\router' => '/Router.php',
                'library\\searchformprocessor' => '/SearchFormProcessor.php',
                'library\\uri' => '/Uri.php',
                'library\\xmleditor' => '/XmlEditor.php',
                'library\\xmlprocessor' => '/XmlProcessor.php'
            );
        }
        $cn = strtolower($class);
        if (isset($classes[$cn])) {
            require __DIR__ . $classes[$cn];
        }
    }
);
// @codeCoverageIgnoreEnd
